on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04   
    steps:
      - name: Login to Azure
        uses: hyperskill/azure-login@v3.0.0
        with:
          # Azure client id
          client_id: 3f02b9f2-7063-4b44-9d75-937262d625b9
          # Azure client secret
          client_secret: 8988Q~cEX7WrtV7A0hoQhgfa0fTvN5EBSTadzbg9
          # Azure subscription id
          subscription_id: dd2fe2ae-28d1-4517-b12b-b56258ece7d8
          # Azure tenant id
          tenant_id: d82f5415-32ab-48fc-83f8-6a2b5b8df728
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Plan
        run: terraform plan
        
      - name: Terraform Apply
        run: terraform apply -auto-approve
      - name: Show Resources List
        run: terraform state list
